feat: Modify filter to process n-dimentional input
Onepredict/onebone pull request #75
Opened 2022-02-25 02:20 UTC by kyunghwan-onepredict

## Summary
_Write the summary about this PR._

- filter 함수들이 2차원 이상의 입력을 처리할 수 있도록 수정

## Changes
_Write changes in detail._

- 

## How to Test?
_Write a way to test the changes._

- `make test`

## Checklist

- [ ] Do you pass all the tests?
- [ ] Do you write the changes on document such as README?

2022-02-25 02:36 UTC, Kangwhi-Kim commented on onebone/signal/fft.py
Summary 부분에 1D signal filter라고 명시해주면 좋을 것 같습니다.

2022-02-25 02:43 UTC, Kangwhi-Kim requested changes

2022-02-25 02:43 UTC, Kangwhi-Kim commented on onebone/signal/fft.py
Summary 부분에 1D signal FFT라고 명시해주면 좋을 것 같습니다.

2022-02-25 02:43 UTC, Kangwhi-Kim commented on onebone/signal/filter.py
Summary 부분에 1D signal filter라고 명시해주면 좋을 것 같습니다. (lowpass, bandpass, bandstop, highpass)

2022-02-25 02:43 UTC, Kangwhi-Kim commented on onebone/signal/filter.py
> +
위와 아래 예제에 대한 간단한 설명을 해주면 좋을 것 같습니다.
[예](https://github.com/Onepredict/onebone/blob/f1cfb15de6342816eedc2c2377a5f39688ca7716/onebone/math/integrate.py#L69-L96)

2022-02-25 02:43 UTC, Kangwhi-Kim commented on onebone/signal/filter.py
> +
위와 아래 예제에 대한 간단한 설명을 해주면 좋을 것 같습니다.
[예](https://github.com/Onepredict/onebone/blob/f1cfb15de6342816eedc2c2377a5f39688ca7716/onebone/math/integrate.py#L69-L96)

2022-02-25 02:43 UTC, Kangwhi-Kim commented on onebone/signal/filter.py
> +
위와 아래 예제에 대한 설명을 해주면 좋을 것 같습니다.
[예](https://github.com/Onepredict/onebone/blob/f1cfb15de6342816eedc2c2377a5f39688ca7716/onebone/math/integrate.py#L69-L96)제

2022-02-25 04:53 UTC, kyunghwan-onepredict commented on onebone/signal/fft.py
반영하였습니다.

2022-02-25 04:53 UTC, kyunghwan-onepredict commented on onebone/signal/filter.py
반영하였습니다.

2022-02-25 04:53 UTC, kyunghwan-onepredict commented on onebone/signal/filter.py
> +
반영하였습니다.

2022-02-25 04:53 UTC, kyunghwan-onepredict commented on onebone/signal/filter.py
> +
반영하였습니다.

2022-02-25 04:53 UTC, kyunghwan-onepredict commented on onebone/signal/filter.py
> +
반영하였습니다.

2022-03-04 02:55 UTC, Kangwhi-Kim approved these changes
Good!

2022-03-04 02:59 UTC, merged