feat: Add wavelet denoising
Onepredict/onebone pull request #80
Opened 2022-03-08 08:10 UTC by kyunghwan-onepredict

## Summary
_Write the summary about this PR._

- wavelet denoising 함수 추가. 

![image](https://user-images.githubusercontent.com/86699249/157193163-f15e716f-dcc4-43ae-b00e-336e7809e6e3.png)

## Changes
_Write changes in detail._

- 

## How to Test?
_Write a way to test the changes._

- `python tests/signal/test_wavelet_denosing.py`

## Checklist

- [ ] Do you pass all the tests?
- [ ] Do you write the changes on document such as README?

2022-03-08 08:21 UTC, Kangwhi-Kim requested changes

2022-03-08 08:21 UTC, Kangwhi-Kim commented on onebone/signal/denoise.py
> +    threshold = np.sqrt(2 * np.log(signal.size)) * np.median(np.abs(coeff[-1])) / 0.6745
0.6745는 wavelet을 구현하는데 있어서 어떤 상수인가요?

2022-03-08 09:49 UTC, JunghoPark-OnePredict commented on tests/signal/test_wavelet_denosing.py
> +    expected_answer = np.array(
expected answer는 어떤 기준에 의해 만드신거가요?

2022-03-09 05:54 UTC, isingmodel commented on onebone/signal/__init__.py
> +from .denoise import wavelet_denoising
signal.filter가 signal denoising을 포함한다고 생각합니다. signal.denoising을 signal.filter에 넣는 것은 어떨까요?

2022-03-10 03:45 UTC, kyunghwan-onepredict commented on onebone/signal/denoise.py
> +    threshold = np.sqrt(2 * np.log(signal.size)) * np.median(np.abs(coeff[-1])) / 0.6745
![image](https://user-images.githubusercontent.com/86699249/157584338-bbeeb9c4-c29b-467d-8142-235f09dffc0f.png)
matlab의 wavelet denoising 관련 영상인데, universal threshold 공식을 이렇게 정의했습니다.
기존 모터의 wavelet code에서도 이렇게 구현되어있어서 그대로 사용하였습니다.

2022-03-10 03:49 UTC, kyunghwan-onepredict commented on tests/signal/test_wavelet_denosing.py
> +    expected_answer = np.array(
현재 함수 결과 기준으로 만들었습니다. 눈으로 봤을때 어느정도 denoising 되었다고 판단해서 결과값을 그대로 넣었습니다.
더 좋은 테스트 방법 있으면 의견 부탁드립니다.

2022-03-10 03:52 UTC, kyunghwan-onepredict commented on onebone/signal/__init__.py
> +from .denoise import wavelet_denoising
filter가 더 큰 개념이라고 생각되어 denoise는 따로 분리하였습니다.
사용시에는 onebone.signal.wavelet_denoising으로 쓸 것 같아 파일을 따로 분리해보았는데 filter에 넣을지 고민이 되네요.
@Kangwhi-Kim 어떻게 생각하시나요?

2022-03-10 05:13 UTC, JunghoPark-OnePredict commented on tests/signal/test_wavelet_denosing.py
> +    expected_answer = np.array(
넵, 확인하였습니다. 아마 기존 함수를 이용하는 것이니 이 정도 테스트도 괜찮을것 같습니다.

2022-03-16 02:02 UTC, Kangwhi-Kim requested changes

2022-03-16 02:02 UTC, Kangwhi-Kim commented on onebone/signal/__init__.py
> +from .denoise import wavelet_denoising
denoise.py에 넣어도 괜찮을 것 습니다.

2022-03-16 02:02 UTC, Kangwhi-Kim approved these changes
고생하셨습니다

2022-03-16 02:17 UTC, merged