Feature/singal co relations
Onepredict/onebone pull request #84
Opened 2022-03-08 15:53 UTC by isingmodel

## Summary
_Write the summary about this PR._

- Phase Alignment feature added

## Changes
_Write changes in detail._

- Phase Alignment feature added

## How to Test?
_Write a way to test the changes._

- You may check tests/feature/test_correlations.py

## Checklist

- [예쓰] Do you pass all the tests?
- [Nope] Do you write the changes on document such as README?

2022-03-09 06:39 UTC, kyunghwan-onepredict requested changes

2022-03-09 06:39 UTC, kyunghwan-onepredict commented on onebone/feature/correlations.py
> +    :math:`w_{j, f}` denotes phase of singal :math:`j` at frequency :math:`f`.
typo: singal -> signal

2022-03-09 06:39 UTC, kyunghwan-onepredict commented on onebone/feature/correlations.py
> +    fs : int or float, default=1
- default 값 위에는 없는데 docs에만 있네요.
- 별개로 fs는 꼭 입력받아야하는 값이니 default 안쓰는게 어떨까요?

2022-03-09 06:39 UTC, kyunghwan-onepredict commented on tests/feature/test_correlations.py
> +def check_phase_alignment():
함수이름 check_phase_alignment -> test_phase_alignment
test로 시작해야 pytest에서 체크해줍니다.

2022-03-09 06:39 UTC, kyunghwan-onepredict commented on onebone/feature/correlations.py
> +    y : numpy.ndarray of shape (n, signal_length)
무조껀 (n, signal_length) 사이즈만 받아야하니 아래 예외처리에서 len(shape) != 2 이면 에러 raise 하는건 어떨까요?

2022-03-09 06:39 UTC, kyunghwan-onepredict commented on onebone/feature/correlations.py
> +    """
Examples 추가 필요

2022-03-09 06:39 UTC, kyunghwan-onepredict commented on onebone/feature/correlations.py
> +    phase_alignment = np.abs(np.mean(normed_density, axis=0))
(개념적인 질문)
phase alignment 결과가 여러 신호의 주파수 도메인에서의 평균값이다 정도로 이해하면 될까요?
저는 phase alignment가 예를 들어 (3, 1000) 이 들어왔을때 phase가 잘 맞춰진 (3, 1000) output을 내는 것이라고 생각했어서요.

2022-03-09 12:27 UTC, isingmodel commented on onebone/feature/correlations.py
> +    phase_alignment = np.abs(np.mean(normed_density, axis=0))
주파수 도메인에서 unit phase vector을 더한 결과입니다. 일종의 평균값이 맞아요.

2022-03-09 12:29 UTC, isingmodel commented on onebone/feature/correlations.py
> +    :math:`w_{j, f}` denotes phase of singal :math:`j` at frequency :math:`f`.
지적해주신 사항들 모두 변경했습니다.

2022-03-10 02:36 UTC, kyunghwan-onepredict commented on onebone/feature/correlations.py
> +    :math:`w_{j, f}` denotes phase of singal :math:`j` at frequency :math:`f`.
```suggestion
    :math:`w_{j, f}` denotes phase of signal :math:`j` at frequency :math:`f`.
```
이 오타도 수정되면 좋겠습니다.

2022-03-10 02:37 UTC, kyunghwan-onepredict commented
```suggestion
    :math:`w_{j, f}` denotes phase of signal :math:`j` at frequency :math:`f`.
```
이 오타도 수정되면 좋겠습니다.

2022-03-10 02:38 UTC, kyunghwan-onepredict commented on onebone/feature/correlations.py
> +    :math:`w_{j, f}` denotes phase of singal :math:`j` at frequency :math:`f`.
```suggestion
    :math:`w_{j, f}` denotes phase of signal :math:`j` at frequency :math:`f`.
```
이 오타도 수정되면 좋겠습니다.

2022-03-10 03:57 UTC, Kangwhi-Kim requested changes

2022-03-10 03:57 UTC, Kangwhi-Kim commented on onebone/feature/correlations.py
> +    density = np.fft.fft(y)[:, : y.shape[-1] // 2]
```suggestion
    freq = np.fft.rfftfreq(y.shape[-1], d=1 / fs)[:-1]
    density = np.fft.rfft(y)[:, : -1]
```
TMI긴 한데, 같은 결과가 나옵니다.
취향으로 선택하시면 될 것 같습니다.

2022-03-10 03:57 UTC, Kangwhi-Kim commented on onebone/feature/correlations.py
> +    phase_alignment = np.abs(np.mean(normed_density, axis=0))
@isingmodel 
어떤 주파수 성분에 대한 각 신호의 unit vector들을 평균한 결과는, 그 주파수 성분에서의 phase들을 평균화시키지만 amplitude는 작아질 것 같습니다. 예를 들어, `0+1j`와 `1+0j`를 평균하면 `0.5+0.5j`가 나오는데 phase는 평균값(45도)이지만 amplitude(0.707)가 다른값이 나옵니다.
저는 phase만 평균화시켜 `1/root(2) + 1/root(2) * j 가 나오기를 기대하는데, 여기에 대해 기범님 의견은 어떠하신가요?

2022-03-10 04:23 UTC, isingmodel commented on onebone/feature/correlations.py
> +    phase_alignment = np.abs(np.mean(normed_density, axis=0))
@Kangwhi-Kim 이 함수의 목적이 바로 그 작아지는 값입니다. 특정 frequency에서 signal들의 phase가 비슷하다면 phase alignment의 결과값이 큰 값(~1)이 나오고, signal들의 phase가 uniform random으로 분포한다면 phase alignment의 값이 0 근처로 나오겠죠.  phase alignment의 값에 따라 각 signal들의 phase 정렬 정도를 알 수 있습니다.

2022-03-10 04:41 UTC, isingmodel commented on .gitignore
> +.idea
pycharm cache입니다. pycharm 사용하시는 분들은  열람하는 폴더에 다 생기더라구요

2022-03-10 05:45 UTC, kyunghwan-onepredict approved these changes
고생하셨습니다! 강휘님 comment 마무리되면 merge 해주시면됩니다.

2022-03-10 05:55 UTC, Kangwhi-Kim requested changes

2022-03-10 05:55 UTC, Kangwhi-Kim commented on onebone/feature/correlations.py
> +    phase_alignment = np.abs(np.mean(normed_density, axis=0))
@isingmodel 아하, 결국 이 함수의 목적이 각 주파수 성분들에서 phase의 alignment를 보는 것에 있겠네요?

2022-03-10 05:56 UTC, isingmodel commented on onebone/feature/correlations.py
> +    phase_alignment = np.abs(np.mean(normed_density, axis=0))
@Kangwhi-Kim 맞습니다!

2022-03-10 08:07 UTC, Kangwhi-Kim approved these changes
저는 더이상 리뷰할게 없네요, 멋진 함수 만드시느라 고생하셨습니다.

2022-03-10 08:14 UTC, merged

2022-03-14 02:58 UTC, Kangwhi-Kim commented
@all-contributors please add @isingmodel for code