feature: Add hampel filter
Onepredict/onebone pull request #85
Opened 2022-03-09 12:40 UTC by akangel0307

q

## Summary
_Write the summary about this PR._

- 분석할 data 에서 Outlier 및 Nan data 를 제거해주기 위한 filter
- 아래는 해당 filter 를 사용하면 나오는 결과로, 사용자가 window size 를 조절하여 filter 를 하면 Outlier 와 Nan data 가 제거가 됩니다. 
![image](https://user-images.githubusercontent.com/92007351/157443285-ac48520a-3bc4-44f2-a524-aaf4cf24ae58.png)

## Changes
_Write changes in detail._

- 

## How to Test?
_Write a way to test the changes._

- python tests/signal/test_hampel_filter.py

## Checklist

- [ ] Do you pass all the tests?
- [ ] Do you write the changes on document such as README?

2022-03-09 13:51 UTC, isingmodel commented
* 새로 pr을 만드셨는데, 이전 PR은 close하시는 것이 좋을 것 같습니다. 
* @kyunghwan-onepredict 저도 기범님 말씀에 동의하는데 현재 hampel-filter 를 경환님이 만든 filter.py 쪽에 def 로 포함시키는게 나을까요?? -> 이렇게 하시는 것이 좋을 것 같아요.

2022-03-09 14:11 UTC, isingmodel commented on onebone/signal/hampel_filter.py
> +    filtered_series : numpy.ndarray
onebone의 description은 일단 영어가 원칙인 거 같은데 @kyunghwan-onepredict님 맞나요?

2022-03-09 14:11 UTC, isingmodel commented on onebone/signal/hampel_filter.py
> +    Parameters
설명이 빠진 parameter들이 있네요.

2022-03-09 14:11 UTC, isingmodel commented on onebone/signal/hampel_filter.py
> +                      필터로 인해 Outlier 값이 제거된 값이 나오게 됩니다.
hampel filter의 원리에 대한 (간략한) 설명이 없는 것 같습니다.

2022-03-09 14:11 UTC, isingmodel commented on onebone/signal/hampel_filter.py
> +                      이는 AutoWindow=True 로 개선할 예정입니다.
개선이 된 이후에 이 pr이 완성되는 거겠죠?

2022-03-09 14:11 UTC, isingmodel commented on onebone/signal/hampel_filter.py
> +    k = 1.4826  # scale factor for Gaussian distribution
왜 이 값음 hard coding되어있나요

2022-03-09 14:11 UTC, isingmodel commented on tests/signal/test_hampel_filter.py
> +    first_feature = hampel_filter.hampel_filter(timeseries_data(), 3)[0]
test function은 원하는 결과가 나오는지 테스트하는 용도이므로, 작성하신 테스트코드는 테스트라는 목적에 맞지 않는 것 같습니다.

2022-03-09 15:47 UTC, akangel0307 commented
> 

넵 해당 내용은 지금 제가 하는 작업들이 끝나면 바로 def 형태로 넣겠습니다.

- [ ] 수정 작업 끝나면 마지막에 진행후 체크하기

2022-03-10 00:42 UTC, isingmodel commented on tests/signal/test_hampel_filter.py
> +def test_hampel_filter():
* test function은 자동 테스트용이라 plot으로 확인하는 것은 별로 의미가 없습니다. 
* 제 생각에는 noise 이전 시그널과 hampel_filter(noisy_signal) 사이의 오차가 적다는 것으로 assert를 구성할 것 같습니다. (onebone의 다른 함수 test code 참조)

2022-03-10 02:14 UTC, kyunghwan-onepredict commented
> * @kyunghwan-onepredict 저도 기범님 말씀에 동의하는데 현재 hampel-filter 를 경환님이 만든 filter.py 쪽에 def 로 포함시키는게 나을까요?? -> 이렇게 하시는 것이 좋을 것 같아요.

네 filter.py로 옮기시죠 ㅎ

2022-03-10 02:21 UTC, kyunghwan-onepredict commented on onebone/signal/hampel_filter.py
> +    if type(window_size) != int:
isinstance() 구문을 쓰시면 좋을것 같네요.
https://github.com/Onepredict/onebone/blob/50b75aac50634b2672b82b1a83881f076a06259b/onebone/feature/tacholess.py#L151

2022-03-10 02:24 UTC, kyunghwan-onepredict commented on onebone/signal/hampel_filter.py
> +    >>> ax1 = plt.subplot(2,2,1)
example에 plt를 쓴다면 결과 이미지를 함께 넣어주거나 그게 아니라면 일반 값으로 하면 좋겠네요.
이미지 예시: https://github.com/Onepredict/onebone/pull/80

2022-03-10 16:29 UTC, akangel0307 commented on onebone/signal/hampel_filter.py
> +
감사합니다. 수정 완료하였습니다.

2022-03-10 16:29 UTC, akangel0307 commented on onebone/signal/hampel_filter.py
> +    Parameters
감사합니다. 수정 완료하였습니다.  
n_sigma 와 auto_window 에 대한 설명을 추가하였습니다.

2022-03-10 16:29 UTC, akangel0307 commented on onebone/signal/hampel_filter.py
> +    filtered_series : numpy.ndarray
감사합니다. 영어로 변환 하였습니다.

2022-03-10 16:29 UTC, akangel0307 commented on onebone/signal/hampel_filter.py
> +def hampel_filter(array, window_size, n_sigmas=3, Autowindow=False):
> 같습니다

넵 array -> series 로 수정하였습니다.

2022-03-10 16:30 UTC, akangel0307 commented on onebone/signal/hampel_filter.py
> +    """
> 일반적으로 함수 description(parameters, returns etc)은 최상단에 위치합니다.

감사합니다! import 아래, def 시작 전에 description 위치를 수정하였습니다.

2022-03-10 16:31 UTC, akangel0307 commented on onebone/signal/hampel_filter.py
> +
> 또한 onebone에서는 lower case만 쓰는 걸 추천하기 때문에 Autowindow를 autowindow로 변경하면 좋을 것 같습니다.

수정 완료하였습니다. 감사합니다.

2022-03-10 16:32 UTC, akangel0307 commented on onebone/signal/hampel_filter.py
> +
> 

참고 주신 내용 보고 수정하였는데 한번 확인 부탁드립니다. 감사합니다!

2022-03-10 16:35 UTC, akangel0307 commented on onebone/signal/hampel_filter.py
> +    k = 1.4826  # scale factor for Gaussian distribution
> 왜 이 값음 hard coding되어있나요
k 상수의 경우, MAD * k = 표준편차 의 식을 활용할때 필요하며 해당값은 아래와 같이 도출됩니다. 
이 내용을 주석으로 추가하는게 나을까요? 
<img width="563" alt="image" src="https://user-images.githubusercontent.com/92007351/157710190-5332d238-b523-42b8-8868-53e66d295d12.png">

2022-03-10 16:37 UTC, akangel0307 commented on onebone/signal/hampel_filter.py
> +    filtered_series : numpy.ndarray
description 수정 완료하였습니다. 감사합니다.

2022-03-10 16:38 UTC, akangel0307 commented on onebone/signal/hampel_filter.py
> +    Parameters
> 설명이 빠진 parameter들이 있네요.
설명이 빠진 두개의 parameter 에 대해 추가하였습니다. 감사합니다.

2022-03-10 16:40 UTC, akangel0307 commented on onebone/signal/hampel_filter.py
> +                      이는 AutoWindow=True 로 개선할 예정입니다.
> 개선이 된 이후에 이 pr이 완성되는 거겠죠?

구현하고 싶었던 함수이나, 현재는 고려중입니다. 우선 개선하여 PR 완성 시키는 방향이 될 수 있게 해보겠습니다.

2022-03-11 03:24 UTC, isingmodel commented on onebone/signal/hampel_filter.py
> +            )
window_median과 S_k 모두 `filtered_series[(i - window_size) : (i + window_size)]`를 쓰는데, 이것을 따로 변수로 선언한 뒤에 window_median과 S_k 계산에 사용하면 코드가 더 깔끔해질 것 같습니다.

2022-03-11 03:24 UTC, isingmodel commented on onebone/signal/hampel_filter.py
> +    k = 1.4826  # scale factor for Gaussian distribution
저번에 쓰신 댓글을 확인했습니다. 그렇다면 series의 분포가 normal이라는 가정하에 적용되는 filter군요?

2022-03-11 03:24 UTC, isingmodel commented on onebone/signal/hampel_filter.py
> +    elif autowindow is True:
autowindow is True일 때를 대비해, autowindow is False를 적절히 모듈화시켜두면(함수화 등등) 코드의 중복을 피할 수 있을 것 같네요.

2022-03-13 03:03 UTC, isingmodel commented on onebone/signal/hampel_filter.py
> +) -> Tuple[np.ndarray, list]:
```suggestion
def hampel_filter(
    series: np.ndarray, window_size: int, n_sigmas: float = 3, autowindow: bool=False
) -> Tuple[np.ndarray, list]:
```

2022-03-13 03:03 UTC, isingmodel commented on onebone/signal/hampel_filter.py
> +
optional input도 typehint를 넣읍시다

2022-03-13 14:00 UTC, akangel0307 commented on onebone/signal/hampel_filter.py
> +) -> Tuple[np.ndarray, list]:
> 

뺴먹은 내용 도와주셔서 감사합니다 !!!

2022-03-13 14:02 UTC, akangel0307 commented on onebone/signal/hampel_filter.py
> +            )
> 

말씀해주신 대로 다소 이름은 촌스럽지만 real_window_size 로 변수 선언하였습니다..! 감사합니다 ㅎㅎㅎ

2022-03-13 14:03 UTC, akangel0307 commented on onebone/signal/hampel_filter.py
> +            window_median = np.median(filtered_series[(i - window_size) : (i + window_size)])
> `window_median = np.median(filtered_series[(i - window_size) : (i + window_size)])` 사실상 window의 크기가 2*window_size이네요?

넵 맞아요 사용자가 인지할수있게 2*window_size 로 적용된다고 설명을 추가해야겠네요

2022-03-13 14:04 UTC, akangel0307 commented on onebone/signal/hampel_filter.py
> +def hampel_filter(series: np.ndarray, window_size: int, n_sigmas=3, autowindow=False) -> np.ndarray:
> output이 2개임을 확인해주세요

도와주셔서 감사합니다! Tuple[np.ndarray, list] 로 수정하였습니다.

2022-03-13 14:04 UTC, akangel0307 commented on onebone/signal/hampel_filter.py
> +"""
> onebone의 다른 함수들 확인해보세요.

넵 ㅠㅠ 제가 임의로 그냥 옮겨버려서 참고를 안하고 진행항것 같습니다. 말씀하신대로 수정하였습니다

2022-03-13 14:05 UTC, akangel0307 commented on onebone/signal/hampel_filter.py
> +    >>> ax1 = plt.subplot(2,2,1)
> example에 plt를 쓴다면 결과 이미지를 함께 넣어주거나 그게 아니라면 일반 값으로 하면 좋겠네요. 이미지 예시: #80

네! 경환님 코드 참고하여 이미지를 함꼐 넣어주었습니다. 감사합니다!

2022-03-13 14:09 UTC, akangel0307 commented on tests/signal/test_hampel_filter.py
> +def test_hampel_filter():
> * test function은 자동 테스트용이라 plot으로 확인하는 것은 별로 의미가 없습니다.
> * 저라면 noise 이전 시그널과 hampel_filter(noisy_signal) 사이의 오차가 적다는 것으로 assert를 구성할 것 같습니다. (onebone의 다른 함수 test code 참조)

감사합니다. numpy.testing.assert_array_almost_equal  의 함수를 추가하여, 필터된 데이터와 outlier 가 없는 데이터를 비교하였습니다. 다만, decimal 을 default 값인 6으로 하면 오류가 나서, decimal=0 으로 선언해주었습니다. 

실제로 완벽하게 똑같은 non_outlier_data 를 만들려는게 아니고, 비슷하게 만들려는 것이다 보니 어느정도 비슷하면 통과 시키기 위헤 decimal=0 으로 설정하였습니다.

2022-03-13 14:10 UTC, akangel0307 commented on tests/signal/test_hampel_filter.py
> +    first_feature = hampel_filter.hampel_filter(timeseries_data(), 3)[0]
> test function은 원하는 결과가 나오는지 테스트하는 용도이므로, 작성하신 테스트코드는 테스트라는 목적에 맞지 않는 것 같습니다.

다시 재 작성하여 test function 을 구현해보았는데 한번 다시 확인 부탁드립니다..! 좋은 지적 감사합니다.

2022-03-13 15:35 UTC, isingmodel commented on onebone/signal/hampel_filter.py
> +            real_window_size = filtered_series[(i - window_size) : (i + window_size)]
windowing한 부분을 real_window_size라고 명명하는 것은 이상한 것 같습니다.

2022-03-13 15:35 UTC, isingmodel commented on onebone/signal/hampel_filter.py
> +        for i in range((window_size), (len(filtered_series) - window_size)):
input의 window size가 n일 때, 실제 window size는 n*2로 작동합니다. 이 부분의 수정이 필요해요.

2022-03-14 02:42 UTC, Kangwhi-Kim requested changes

2022-03-14 02:42 UTC, Kangwhi-Kim commented on onebone/signal/hampel_filter.py
> +            """
해당 수식은 코드라인에서의 주석보다 docs의 description section에 표기하는 것이 좋을 것 같습니다.

2022-03-14 02:42 UTC, Kangwhi-Kim commented on onebone/signal/hampel_filter.py
> +    if autowindow is False:
`autowindow`의 default는 `False` 이므로, 굳이 if문으로 분기를 나누지 않아도 될 것 같습니다.
```suggestion

```

2022-03-14 02:42 UTC, Kangwhi-Kim commented on onebone/signal/hampel_filter.py
> +        raise AttributeError("We are preparing to provide a function")
해당 PR에서 `autowindow` 기능을 구현하지 않으시다면 `def` 에서 `autowindow` parameter를 제거한 후 다음과 같이 표기해주는 것이 좋을 것 같습니다.
```suggestion
        # TODO: window size를 지정 및 가장 유사한 graph로 후보군을 정리해주는 코드 구현 하고싶음

```

2022-03-14 02:42 UTC, Kangwhi-Kim commented on tests/signal/test_hampel_filter.py
> +        import matplotlib.pyplot as plt
import 문은 스크립트 상단에 위치를 요청드립니다.

2022-03-14 02:42 UTC, Kangwhi-Kim commented on tests/signal/test_hampel_filter.py
> +from onebone.signal import hampel_filter
`onebone/signal/__init__.py`에 
```python
from onebone.signal.hampel_filter import hampel_filter
...
__all__ = [..., 'hampel_filter']

```
다음과 같이 작성하여 상세한 모듈이름이 불러오지 않고도 함수를 불러올 수 있습니다.

2022-03-14 02:42 UTC, Kangwhi-Kim commented on tests/signal/test_hampel_filter.py
> +    filtered_data = hampel_filter.hampel_filter(timeseries_data(), window_size)[0]
10 line 피드백 반영후,
```suggestion
    filtered_data = hampel_filter(timeseries_data(), window_size)[0]
```

2022-03-14 02:42 UTC, Kangwhi-Kim commented on tests/signal/test_hampel_filter.py
> +    perfect_data = timeseries_data(num_outlier=0)
1. 순서만 바꾸면 함수 호출 횟수를 줄일 수 있습니다.
2. 노이즈가 없는 데이터는 `origin_data`로 노이즈가 있는 변수는 `noisy_data`가 좋을 것 같습니다.
```suggestion
    origin_data = timeseries_data(num_outlier=0)
    noisy_data = timeseries_data(num_outlier=10)
    filtered_data = hampel_filter.hampel_filter(noisy_data, window_size)[0]

```

2022-03-14 02:42 UTC, Kangwhi-Kim commented on tests/signal/test_hampel_filter.py
> +    check_window_region = [window_size * 2, len(timeseries_data()) - window_size * 2]
```suggestion
    check_window_region = [window_size * 2, len(origin_data) - window_size * 2]
```

2022-03-14 14:29 UTC, akangel0307 commented on onebone/signal/hampel_filter.py
> +        for i in range((window_size), (len(filtered_series) - window_size)):
> input의 window size가 n일 때, 실제 window size는 n*2로 작동합니다. 이 부분의 수정이 필요해요.

코드를 설정한 window size 로만 적용 가능하게 수정하였습니다

2022-03-14 14:31 UTC, akangel0307 commented on onebone/signal/hampel_filter.py
> +            S_k = k * np.median(np.abs(real_window_size - window_median))
> 가능하면, 변수명은 snake_case로 요청드립니다.

넵 MAD 에 k 값을 곱한 변수이기에 MAD_k 로 수정하였습니다. 왠만하면 full name 을 작성하고 싶었으나,, 너무 긴것 같아 MAD_k 로 타협하였습니다. 감사합니다!

2022-03-14 14:33 UTC, akangel0307 commented on onebone/signal/hampel_filter.py
> +    [2] https://github.com/MichaelisTrofficus/hampel_filter
> 

넵 [1] 의 내용으로 구현 가능한 내용이기에, [1] 만 남겨두는게 좋을것 같습니다. 좋은 의견 감사합니다!!

2022-03-14 14:48 UTC, akangel0307 commented on onebone/signal/hampel_filter.py
> +) -> Tuple[np.ndarray, list]:
> 

헛 놓치고 있었던 부분이네요 감사합니다 !

2022-03-14 14:51 UTC, akangel0307 commented on onebone/signal/hampel_filter.py
> +        raise AttributeError("We are preparing to provide a function")
> 해당 PR에서 `autowindow` 기능을 구현하지 않으시다면 `def` 에서 `autowindow` parameter를 제거한 후 다음과 같이 표기해주는 것이 좋을 것 같습니다.

구현해보았으나, 만든 hampel filter 함수를 사용하여, auto window 를 돌려야하므로 삭제하는게 나을 것 같아 구현하지않기로 판단하였습니다 
감사합니다

2022-03-14 14:52 UTC, akangel0307 commented on tests/signal/test_hampel_filter.py
> +from onebone.signal import hampel_filter
> 다.

넵 이전에 기범님께서 이 함수는 경환님이 작성하신 filter.py 에 def 로 넣는게 좋을 거 같다 하셔서 코드가 ㄷ ㅏ수정되면 추가로 바뀔 것 같습니다.

2022-03-14 14:56 UTC, akangel0307 commented on tests/signal/test_hampel_filter.py
> +    perfect_data = timeseries_data(num_outlier=0)
> 1. 순서만 바꾸면 함수 호출 횟수를 줄일 수 있습니다.
> 2. 노이즈가 없는 데이터는 `origin_data`로 노이즈가 있는 변수는 `noisy_data`가 좋을 것 같습니다.

감사합니다. 다만, 이름을 정할때 기존 origin data (노이즈가 존재하는 데이터) 를 hampel filter 를  통해 filter 시키면 노이즈가 제거된 데이터가 되게 되며, 이걸 비교할 지표를 찾다가 임의적으로 ideal 한 데이터를 만들어 비교하기 위해 perfect data 로 설정하였습니다. 

의도가 위와 같다보니 노이즈가 없는 데이터를 origin data 로 설정하는게 조금 고민이됩니다
우선은 말씀해주신대로 수정해놓았습니다!

2022-03-14 23:16 UTC, akangel0307 commented on onebone/signal/hampel_filter.py
> +            real_window_size = filtered_series[(i - window_size) : (i + window_size)]
> windowing한 부분을 real_window_size라고 명명하는 것은 이상한 것 같습니다.

for 문을 삭제하고 코드를 새로 작성하였습니다!

2022-03-15 02:28 UTC, akangel0307 commented on onebone/signal/hampel_filter.py
> +    k = 1.4826  # scale factor for Gaussian distribution
> 저번에 쓰신 댓글을 확인했습니다. 그렇다면 series의 분포가 normal이라는 가정하에 적용되는 filter군요?

넵 맞습니다 !

2022-03-15 07:03 UTC, Kangwhi-Kim requested changes

2022-03-15 07:03 UTC, Kangwhi-Kim commented on onebone/signal/hampel_filter.py
> +    MAD(Median Absolute Deviation) in the window range set by the user.
[여기](https://github.com/Onepredict/onebone/blob/d687041258d6502d946171fb612f53968dab2fb4/onebone/feature/gear.py#L27-L30
)있습니다.

2022-03-15 08:40 UTC, akangel0307 commented on onebone/signal/hampel_filter.py
> +    MAD(Median Absolute Deviation) in the window range set by the user.
> [여기](https://github.com/Onepredict/onebone/blob/d687041258d6502d946171fb612f53968dab2fb4/onebone/feature/gear.py#L27-L30)있습니다.

넵 참고하여 수식 추가하였습니다! 감사합니다

2022-03-16 01:20 UTC, Kangwhi-Kim requested changes

2022-03-16 01:20 UTC, Kangwhi-Kim commented on tests/signal/test_hampel_filter.py
> +    test_hampel_filter(is_plot=True)
plot 기능을 넣으신다면, default는 `is_plot=False` 로 요청드립니다.
`make test`로 testcode가 검증할때 plot 실행이 불필요할 것 같습니다.

2022-03-16 01:20 UTC, Kangwhi-Kim commented on tests/signal/test_hampel_filter.py
> +        plt.close()
plt.show 다음 plt.close가 실행되면 창이 안보이지 않나요?

2022-03-16 01:20 UTC, Kangwhi-Kim commented on tests/signal/test_hampel_filter.py
> +    )
4번중 1번꼴로 테스트 오류가 발생합니다.
테스트 케이스가 문제인지, hampel filter가 문제인지 확인 요청드립니다.
![image](https://user-images.githubusercontent.com/79968466/158497816-1333ee6a-a4e9-4e76-8986-0627c68ad793.png)
![image](https://user-images.githubusercontent.com/79968466/158497898-13f3bba2-21b1-4e9b-91b9-799ce28ec047.png)

2022-03-16 01:25 UTC, Kangwhi-Kim requested changes

2022-03-16 01:25 UTC, Kangwhi-Kim commented on onebone/signal/hampel_filter.py
> +        np.arange(window_size)[None, :] + np.arange(int(len(copy_series) - window_size))[:, None]
`int`를 사용하지 않아도 정수형으로 계산됩니다.
```suggestion
        np.arange(window_size)[None, :] + np.arange(len(copy_series) - window_size)[:, None]
```

2022-03-16 01:32 UTC, Kangwhi-Kim commented on onebone/signal/hampel_filter.py
> +    indexer = (
broadcasting을 활용한 window별로 median를 적용했네요. 배우고갑니다 ㅎㅎ

2022-03-16 01:47 UTC, Kangwhi-Kim requested changes

2022-03-16 01:47 UTC, Kangwhi-Kim commented on onebone/signal/hampel_filter.py
> +    oulier_index = np.where(value < n_sigmas * MAD_k, None, indexer[:, 0])
[100 line](https://github.com/Onepredict/onebone/pull/85/files#diff-4ce7d90e8f2fcd6a396e0e44cf2a9003cf1aefbc0b6c3f64dff040f68a8208d6R100)에서 `value > n_sigmas * MAD_k` 일때 outlier로 판단하여 필터링하므로, 아래와 같이 변경해야 할 것 같습니다.
```suggestion
    oulier_index = np.where(value <= n_sigmas * MAD_k, None, indexer[:, 0])
```

2022-03-16 02:21 UTC, akangel0307 commented on tests/signal/test_hampel_filter.py
> +    )
> 4번중 1번꼴로 테스트 오류가 발생합니다. 테스트 케이스가 문제인지, hampel filter가 문제인지 확인 요청드립니다. ![image](https://user-images.githubusercontent.com/79968466/158497816-1333ee6a-a4e9-4e76-8986-0627c68ad793.png) ![image](https://user-images.githubusercontent.com/79968466/158497898-13f3bba2-21b1-4e9b-91b9-799ce28ec047.png)

test 에서의 assert_array_almost_equal 문에 의한 문제 같습니다. 
hampel filter 는 이상치를 제거하여, 합리적으로 생각하는 값으로 대체해주는게 목적이며 window size 를 사용자가 직접 설정해줘 가며 outlier 가 적은 data 를 선정하는 작업이 필요한데, 현재 test code 에서 outlier 를 실행마다 랜덤으로 생성해 주는데 window size 는 계속 하나의 사이즈로 지정해주어 생기는 오류 같습니다. 

따라서, 우선 test code 에서 outlier data 를 하나의 케이스로 고정시켜 해결하였습니다.

2022-03-16 03:54 UTC, akangel0307 commented on onebone/signal/hampel_filter.py
> +    '''
> 렌더링해보니 정상적으로 표현되지 않아 몇 가지 수정사항 요청드리겠습니다.
> 
> 1. 수학식으로 나타내려면 `.. math::` 아래 구문은 들여쓰기를 해야합니다.
> 2. 파이썬의 escape 문법에 의해서 `\r` 같은 경우는 `\\r`로 작성해야 수식으로 표현됩니다.
> 3. 변수에 대한 설명은 변수 옆에 쓰지 않고, 아래에 다시 내어쓰기를 하여 `Where :math:`m_i` is local median, ...` 으로 표기해주시기 바랍니다. [예제](https://github.com/Onepredict/onebone/blob/d687041258d6502d946171fb612f53968dab2fb4/onebone/feature/gear.py#L27-L38)

넵 수정 완료하였습니다. 감사합니다! 다만, github 에 수식으로 올리는 방법에 대해 찾아보니 마땅히 참고될만한 문서를 찾지못하여 도와주신 예제와 onebone 내용들을 참고하여 작성해 보았는데 한번더 렌더링하여 확인 부탁드립니다!

2022-03-16 03:54 UTC, akangel0307 commented on onebone/signal/hampel_filter.py
> +        :width: 300
> 렌더링 해보니 그림 사이즈를 가로로 두배정도 키우면 화면에 잘 들어 맞을 거 같습니다.

감사합니다. 600 으로 수정하였습니다 !

2022-03-16 03:54 UTC, akangel0307 commented on onebone/signal/hampel_filter.py
> +    MAD_k = k * np.median(np.abs(copy_series[indexer] - window_median_array), axis=1)
> 변수명은 가급적 snake_case로 요청드립니다. mad에 대한 뜻을 docs나 주석에 쓰면 좋겠네요.

넵. snake_case를 자꾸 빼먹네요.. 변경하였고 관련 설명을 docs 에 적어봤습니다.

2022-03-16 03:54 UTC, akangel0307 commented on tests/signal/test_hampel_filter.py
> +    test_hampel_filter(is_plot=True)
> plot 기능을 넣으신다면, default는 `is_plot=False` 로 요청드립니다. `make test`로 testcode가 검증할때 plot 실행이 불필요할 것 같습니다.

네. 감사합니다 수정하였습니다.

2022-03-16 03:54 UTC, akangel0307 commented on tests/signal/test_hampel_filter.py
> +        plt.close()
> plt.show 다음 plt.close가 실행되면 창이 안보이지 않나요? 어떤 것을 의도하신 것인가요?

해당 test 함수를 만들때 다른 code 를 참고하며 만들다보니, close 를 해야 하는 것인줄 착각하여 넣었습니다 ! 삭제하였습니다.

2022-03-16 03:54 UTC, akangel0307 commented on onebone/signal/hampel_filter.py
> +        np.arange(window_size)[None, :] + np.arange(int(len(copy_series) - window_size))[:, None]
> `int`를 사용하지 않아도 정수형으로 계산됩니다.

감사합니다! 수정하였습니다.

2022-03-16 03:54 UTC, akangel0307 commented on onebone/signal/hampel_filter.py
> +    indexer = (
> broadcasting을 활용한 window별로 median를 적용했네요. 배우고갑니다 ㅎㅎ

앗,,, 칭찬에 약하다보니 부끄럽네요 ㅎㅎ,,, 감사합니다 !! 저도 강휘님 피드백에 많이 배우고 있습니다

2022-03-16 03:54 UTC, akangel0307 commented on onebone/signal/hampel_filter.py
> +    oulier_index = np.where(value < n_sigmas * MAD_k, None, indexer[:, 0])
> [100 line](https://github.com/Onepredict/onebone/pull/85/files#diff-4ce7d90e8f2fcd6a396e0e44cf2a9003cf1aefbc0b6c3f64dff040f68a8208d6R100)에서 `value > n_sigmas * MAD_k` 일때 outlier로 판단하여 필터링하므로, 아래와 같이 변경해야 할 것 같습니다.

엇 맞네요 감사합니다!!

2022-03-16 15:00 UTC, isingmodel approved these changes

2022-03-17 01:39 UTC, kyunghwan-onepredict commented on onebone/signal/hampel_filter.py
> +    window_size : int,
```suggestion
    window_size : int
```

2022-03-17 01:53 UTC, kyunghwan-onepredict commented on onebone/signal/hampel_filter.py
> +
아래와 같은 형태로 example 만들면 어떨까요.
- import는 굳이 안써도 될것 같습니다.
- example code도 `make format`이 적용된 형태였으면 좋겠습니다. (띄어쓰기 등)
- 신호를 생성하는 코드 -> 이미지 -> filtering 코드 -> filtering 된 이미지. 이와 같은 형태로 작성되면 좋을것 같습니다.

```suggestion
    >>> fs = 100.0
    >>> t = np.linspace(0, 1, int(fs))
    >>> y = np.sin(2 * np.pi * 10.0 * t)
    >>> np.put(y, [9, 13, 24, 30, 45, 51,78], 4)
    <noise signal image>
    
    >>> filtered_signal = hampel_filter.hampel_filter(y, window_size=2)[0]
    <filter 된 image1>
  
    >>> filtered_signal = hampel_filter.hampel_filter(y, window_size=3)[0]
    <filter 된 image2>
    .. image:: https://bit.ly/3t55Dlc #nopa
        :width: 600

```

2022-03-17 01:54 UTC, kyunghwan-onepredict commented on onebone/signal/hampel_filter.py
> +
현재 상태
![image](https://user-images.githubusercontent.com/86699249/158720976-c74b4afa-573c-40b9-83a9-322cbe9ab0cb.png)

2022-03-17 01:57 UTC, kyunghwan-onepredict commented on onebone/signal/hampel_filter.py
> +def hampel_filter(x: np.ndarray, window_size: int, n_sigmas: float = 3) -> Tuple[np.ndarray, list]:
카테고리상 `signal/filter.py` 로 옮기면 좋을 것 같습니다.

2022-03-17 01:58 UTC, kyunghwan-onepredict commented on onebone/signal/hampel_filter.py
> +    """
```suggestion
def hampel_filter(x: np.ndarray, window_size: int, n_sigmas: float = 3) -> Tuple[np.ndarray, list]:
    """
```
불필요한 개행 삭제

2022-03-17 01:59 UTC, kyunghwan-onepredict commented on tests/signal/test_hampel_filter.py
> +    """
```suggestion
def timeseries_data(outlier: bool = True) -> np.ndarray:
    """
```
불필요한 개행 삭제

2022-03-17 01:59 UTC, kyunghwan-onepredict commented on tests/signal/test_hampel_filter.py
> +    make example timeseries
```suggestion
    Make example timeseries.
```
대문자와 마침표 추가

2022-03-17 02:00 UTC, kyunghwan-onepredict commented on tests/signal/test_hampel_filter.py
> +        default = True
```suggestion
    num_outlier : bool, default=True
        You can generate/degenerate timeseries data with example outliers.
```
테스트라 document가 크게 중요하진 않지만 작성하신김에 format을 잘맞추는게 좋아보입니다.

2022-03-17 02:01 UTC, kyunghwan-onepredict commented on onebone/signal/hampel_filter.py
> +def hampel_filter(x: np.ndarray, window_size: int, n_sigmas: float = 3) -> Tuple[np.ndarray, list]:
`signal/__init__.py` 에 함수를 추가하셔야 `from onebone.signal import hampel_filter` 의 형태로 사용가능합니다.
[참고](https://github.com/Onepredict/onebone/blob/main/onebone/signal/__init__.py)

2022-03-17 02:08 UTC, kyunghwan-onepredict commented
@akangel0307 로직적인 부분은 거의 마무리 된것 같고, merge 전에 문서적인 부분에 대해서 주로 코멘트 남겼습니다.
얼마 안남았으니 힘내서 마무리 해봅시다 ㅎ

2022-03-17 02:13 UTC, kyunghwan-onepredict commented on onebone/signal/hampel_filter.py
> +    x : numpy.ndarray
현재 이 함수는 입력으로 들어오길 원하는 data shape이 정해져 있는것 같은데 맞나요?
ex. (signal_length,) or (1, signal_length)

2022-03-17 02:22 UTC, Kangwhi-Kim requested changes

2022-03-17 02:22 UTC, Kangwhi-Kim commented on onebone/signal/hampel_filter.py
> +           For normally distributed data `k` is taken to be `k` = 1.4826
```suggestion
    .. math::
        m_i = median(x_{i-k_{left}}, x_{i-k_{left}+1}, ..., x_{i+k_{right}-1}, x_{i+k_{right}})
    .. math::
        MAD_i = median(|x_{i-k}-m_{i}|,...,|x_{i+k}-m_{i}|)
    .. math::
        {\sigma}_i = {\kappa} * MAD_i
        
    Where :math:`k_{left}` and :math:`k_{right}` are the number of neighbors on the left and right sides, 
    respectively, based on x_i (:math:`k_{left} + k_{right}` = window samples).
    :math:`m_i` is Local median, :math:`MAD_i` is median absolute deviation 
    which is the residuals (deviations) from the data's median.
    :math:`{\sigma}_i` is the MAD may be used similarly to how one would use the deviation for the average.
    In order to use the MAD as a consistent estimator
    for the estimation of the standard deviation :math:`{\sigma}`, one takes :math:`{\kappa} * MAD_i`. 
    :math:`{\kappa}` is a constant scale factor, which depends on the distribution.
    For normally distributed data :math:`{\kappa}` is taken to be :math:`{\kappa}` = 1.4826
```

2022-03-17 02:22 UTC, Kangwhi-Kim commented on onebone/signal/hampel_filter.py
> +           For normally distributed data `k` is taken to be `k` = 1.4826
렌더링 화면 >
![image](https://user-images.githubusercontent.com/79968466/158723450-82058b9e-11f0-4335-82cf-01c6832010ee.png)

2022-03-17 02:22 UTC, Kangwhi-Kim commented on onebone/signal/hampel_filter.py
> +           For normally distributed data `k` is taken to be `k` = 1.4826
제가 이해한 hampel filter에 대해 수식과 설명을 작성했습니다.
필요한 부분 사용하시고 틀린 부분 있다면 수정해서 사용하시면 될 것 같습니다.

2022-03-17 04:38 UTC, akangel0307 commented on onebone/signal/hampel_filter.py
> +def hampel_filter(x: np.ndarray, window_size: int, n_sigmas: float = 3) -> Tuple[np.ndarray, list]:
> 카테고리상 `signal/filter.py` 로 옮기면 좋을 것 같습니다.

넵 말씀해주신대로 아래 수정 내용 수정 후 옮겨놨으며, 기존 hampel_filter.py 는 뻈습니다. 확인 부탁드립니다!

2022-03-17 04:39 UTC, akangel0307 commented on onebone/signal/hampel_filter.py
> +
> 현재 상태 ![image](https://user-images.githubusercontent.com/86699249/158720976-c74b4afa-573c-40b9-83a9-322cbe9ab0cb.png)

감사합니다. 말씀주신게 훨씬 이해하기 좋은거같아서 수정하였습니다.

2022-03-17 04:40 UTC, akangel0307 commented on tests/signal/test_hampel_filter.py
> +        default = True
> 테스트라 document가 크게 중요하진 않지만 작성하신김에 format을 잘맞추는게 좋아보입니다.

format 을 맞추어, return 데이터에 대한 설명, example 도 추가하였습니다!

2022-03-17 04:41 UTC, akangel0307 commented on onebone/signal/hampel_filter.py
> +    x : numpy.ndarray
> 현재 이 함수는 입력으로 들어오길 원하는 data shape이 정해져 있는것 같은데 맞나요? ex. (signal_length,) or (1, signal_length)
> 
> 정해져있는게 맞다면 명시해주는게 좋을것 같습니다.

넵 맞습니다. 말씀해주신대로 The shape of x must be (signal_length,). 라는 문구를 추가하였습니다.

2022-03-17 04:41 UTC, akangel0307 commented on tests/signal/test_hampel_filter.py
> +    """
> 일부 docs 수정이 필요해보입니다.

감사합니다 ! format 을 맞추어, return 데이터에 대한 설명, example 도 추가하였습니다!

2022-03-17 04:42 UTC, akangel0307 commented on onebone/signal/hampel_filter.py
> +           For normally distributed data `k` is taken to be `k` = 1.4826
> 제가 이해한 hampel filter에 대해 수식과 설명을 작성했습니다. 필요한 부분 사용하시고 틀린 부분 있다면 수정해서 사용하시면 될 것 같습니다.

너무 감사합니다 ㅠㅠ 이 부분이 지금 오류도 발생해서 좀 시간이 걸릴 꺼라 생각했는데 완벽하네요

2022-03-17 05:34 UTC, Kangwhi-Kim requested changes

2022-03-17 05:34 UTC, Kangwhi-Kim commented on onebone/signal/filter.py
> +def hampel_filter(x: np.ndarray, window_size: int, n_sigmas: float = 3) -> Tuple[np.ndarray, list]:
docstring의 변수 이름과 다르네요. (다른 곳도 변경 필요)
`n_sigmas` -> `n_sigma`
```suggestion
def hampel_filter(x: np.ndarray, window_size: int, n_sigma: float = 3) -> Tuple[np.ndarray, list]:
```

2022-03-17 05:34 UTC, Kangwhi-Kim commented on onebone/signal/filter.py
> +    filtered_series : numpy.ndarray
input argument가 `x`이니 output argument도 유사하게 `filtered_x`가 좋을 것 같습니다. 변수 이름 변경 필요.
```suggestion
    filtered_x : numpy.ndarray
```

2022-03-17 05:34 UTC, Kangwhi-Kim commented on onebone/signal/filter.py
> +        Returns the index corresponding to Outlier.
대문자 -> 소문자
```suggestion
        A value from which outlier or NaN has been removed by the filter.
    index : list
        Returns the index corresponding to outlier.
```

2022-03-17 05:34 UTC, Kangwhi-Kim commented on onebone/signal/filter.py
> +    # of the standard deviation for Gaussian data.
위에서 정의하는 것보다 [해당 라인](https://github.com/Onepredict/onebone/pull/85/files#diff-8e915f66ac8435177ae6388ae8409b79eb88cfeee286a31ca8e1562162a52cadR473) 위에 표기하는게 좋겠네요.

2022-03-17 05:34 UTC, Kangwhi-Kim commented on onebone/signal/filter.py
> +    ## define sliding window
의도하신게 아니라면, 주석 첫글자는 대문자로, 주석 표기는 `#` 한개만 요청드립니다. (아래 다른 곳도 마찬가지)
```suggestion
    # Define sliding window
```

2022-03-17 05:34 UTC, Kangwhi-Kim commented on onebone/signal/filter.py
> +    k_mad = k * np.median(np.abs(copy_series[indexer] - window_median_array), axis=1)
`k_mad`라는 용어보다 `estimated_sigma`가 좋지 않을까요?

2022-03-17 05:36 UTC, Kangwhi-Kim requested changes

2022-03-17 05:36 UTC, Kangwhi-Kim commented on onebone/signal/filter.py
>  """
- 3-5 line에 선진님 이름과 이메일 주소도 추가 요청드립니다.

2022-03-17 05:38 UTC, Kangwhi-Kim commented on onebone/signal/filter.py
> +
파일 맨 위에 기입 필요.

2022-03-17 05:56 UTC, akangel0307 commented on onebone/signal/filter.py
> +    # of the standard deviation for Gaussian data.
> 위에서 정의하는 것보다 [해당 라인](https://github.com/Onepredict/onebone/pull/85/files#diff-8e915f66ac8435177ae6388ae8409b79eb88cfeee286a31ca8e1562162a52cadR473) 위에 표기하는게 좋겠네요.

넵 수정하였습니다~

2022-03-17 05:56 UTC, akangel0307 commented on onebone/signal/filter.py
> +    ## define sliding window
> 의도하신게 아니라면, 주석 첫글자는 대문자로, 주석 표기는 `#` 한개만 요청드립니다. (아래 다른 곳도 마찬가지)

감사합니다! 모두 적용시켰습니다.

2022-03-17 05:57 UTC, akangel0307 commented on onebone/signal/filter.py
> +    k_mad = k * np.median(np.abs(copy_series[indexer] - window_median_array), axis=1)
> `k_mad`라는 용어보다 `estimated_sigma`가 좋지 않을까요?

이름 설정에 고민이 많았는데, 훨씬 낫네요 ! 감사합니다

2022-03-17 05:58 UTC, akangel0307 commented on onebone/signal/filter.py
>  """
> * 3-5 line에 선진님 이름과 이메일 주소도 추가 요청드립니다.

넵. 만든 함수에 대해서 명시가 필요할까 해서 작성함수 - 제 이름, 주소 넣었습니다.

2022-03-17 06:13 UTC, Kangwhi-Kim requested changes

2022-03-17 06:13 UTC, Kangwhi-Kim commented on onebone/signal/filter.py
> +
Author과 Contact를 경환님것과 합쳐서 아래와 같이 작성요청드립니다. (테스트 코드도 마찬가지)
```suggestion
'''

'''(~모듈 설명~)

- Author: Kyunghwan Kim, Sunjin Kim
- Contact: kyunghwan.kim@onepredict.com, sunjin.kim@onepredict.com

```

2022-03-17 06:13 UTC, Kangwhi-Kim commented on onebone/signal/filter.py
> +    ----------
```suggestion
    Returns
    -------
```

2022-03-17 10:24 UTC, Kangwhi-Kim requested changes

2022-03-17 10:24 UTC, Kangwhi-Kim commented on tests/signal/test_filter.py
> +    num_outlier : bool, default=True
```suggestion
    outlier : bool, default=True
```

2022-03-17 10:26 UTC, Kangwhi-Kim commented on tests/signal/test_filter.py
> +    """
사실, 테스트 코드에 대해서는 docsting 작성을 하지 않으셔도 될 것 같습니다.

2022-03-17 10:29 UTC, akangel0307 commented on tests/signal/test_filter.py
> +    """
> 사실, 테스트 코드에 대해서는 docsting 작성을 하지 않으셔도 될 것 같습니다.

아앗,,, 삭제 하는게 나을까요.. ?

2022-03-17 10:29 UTC, akangel0307 commented on onebone/signal/filter.py
> +    k = 1.4826
> 위치 수정이 안되었네요.

해당라인을 잘못 해석하여 k=1.4826 위라고 하신줄알았습니다. 수정하였습니다!

2022-03-18 08:33 UTC, kyunghwan-onepredict requested changes

2022-03-18 08:33 UTC, kyunghwan-onepredict commented on tests/signal/test_filter.py
> +if __name__ == "__main__":
`if __name__ == "__main__":`
위 코드가 해당 파일에 2개 존재합니다. 합쳐서 정리해주세요.

2022-03-18 08:33 UTC, kyunghwan-onepredict commented on onebone/signal/filter.py
> +    """
```suggestion
    >>> fs = 1000.0
    >>> t = np.linspace(0, 1, int(fs))
    >>> y = np.sin(2 * np.pi * 10.0 * t)
    >>> np.put(y, [13, 124, 330, 445, 651, 775, 978], 3)
    >>> print('noise_signal')
 
    .. image:: https://bit.ly/3JitQu0 #nopa
        :width: 600

    >>> filtered_signal = hampel_filter.hampel_filter(y, window_size=2)[0]
    >>> print('filtered_signal_window=5')

    .. image:: https://bit.ly/3MX92KV #nopa
        :width: 600
 
    >>> filtered_signal = hampel_filter.hampel_filter(y, window_size=3)[0]
    >>> print('filtered_signal_window=10')

    .. image:: https://bit.ly/3JlBion #nopa
        :width: 600
    """
```

2022-03-18 08:33 UTC, kyunghwan-onepredict commented on onebone/signal/filter.py
> +    """
```
    .. image:: https://bit.ly/3MX92KV #nopa
        :width: 600
```
해당 코드 위 아래로 개행을 해줘야 이미지가 제대로 나옵니다. 잘나오는지 확인하고 다시 올려주세요.

2022-03-18 08:33 UTC, kyunghwan-onepredict commented on onebone/signal/filter.py
> +    .. image:: https://bit.ly/3JitQu0 #nopa
`# noqa` 는 필요없어보입니다. 3개 다 지워주세요.

2022-03-18 08:33 UTC, kyunghwan-onepredict commented on onebone/signal/filter.py
> +    >>> print('noise_signal')
example에 print를 쓰기보다 차라리 설명으로 써주시는게 나을것 같네요.
[참고](https://github.com/Onepredict/onebone/blob/7ed7287492cbe17412a983baef83df2d6562d74e/onebone/signal/filter.py#L41-L76)
해당 함수의 sphinx 결과도 보고 참고해주세요.

2022-03-19 16:45 UTC, akangel0307 commented on onebone/signal/filter.py
> +    >>> print('noise_signal')
> example에 print를 쓰기보다 차라리 설명으로 써주시는게 나을것 같네요. [참고](https://github.com/Onepredict/onebone/blob/7ed7287492cbe17412a983baef83df2d6562d74e/onebone/signal/filter.py#L41-L76) 해당 함수의 sphinx 결과도 보고 참고해주세요.

sphinx 결과 보고 plt. 로 코드 작성 주석으로 설명 적어놓았 습니다!

2022-03-19 16:46 UTC, akangel0307 commented on onebone/signal/filter.py
> +    .. image:: https://bit.ly/3JitQu0 #nopa
> `# noqa` 는 필요없어보입니다. 3개 다 지워주세요.

넵 감사합니다

2022-03-19 16:46 UTC, akangel0307 commented on onebone/signal/filter.py
> +    """
> ```
>     .. image:: https://bit.ly/3MX92KV #nopa
>         :width: 600
> ```
> 
> 해당 코드 위 아래로 개행을 해줘야 이미지가 제대로 나옵니다. 잘나오는지 확인하고 다시 올려주세요.

네! 확인해보고 다시 수정했어요 확인 부탁드려요!

2022-03-19 16:46 UTC, akangel0307 commented on tests/signal/test_filter.py
> +if __name__ == "__main__":
> `if __name__ == "__main__":` 위 코드가 해당 파일에 2개 존재합니다. 합쳐서 정리해주세요.

맨 아래에 합쳐놨습니다! 감사합니다 :)

2022-03-21 00:02 UTC, Kangwhi-Kim requested changes

2022-03-21 02:55 UTC, akangel0307 commented on onebone/signal/filter.py
> +    k = 1.4826
> `k`에 대한 변수 선언을 465 line 위로 요청드립니다. `k`가 사용되는 코드 근처에 있는게 좋을 것 같아요.

엇 맞는 말씀이시네요 수정하였습니다! 감사합니다

2022-03-21 08:37 UTC, kyunghwan-onepredict approved these changes
Excellent!

2022-03-21 08:40 UTC, kyunghwan-onepredict commented
@all-contributors please add @akangel0307 for code

2022-03-21 08:44 UTC, Kangwhi-Kim approved these changes
고생많으셨습니다 선진님!
나중에 노이즈필터링할때 활용해봐야겠네요ㅎㅎ

2022-03-21 08:48 UTC, merged