feature: make clean으로 .pyc가 제대로 지워지지 않는 현상 버그 수정(#89)
Onepredict/onebone pull request #90
Opened 2022-03-15 01:13 UTC by castedice

## Summary
프로젝트 내의 모든 .pyc를 찾지 못하는 현상을 발견하여 Makefile을 수정
OS마다 find 문법이 조금씩 상이하여 어떤 플랫폼에서도 작동할 수 있도록
python으로 구현하였음
링크: https://stackoverflow.com/questions/28991015/python3-project-remove-pycache-folders-and-pyc-files

## Changes
Makefile 수정

## How to Test?
make test 이후 make clean으로 확인

## Checklist

- [v] Do you pass all the tests?
- [v] Do you write the changes on document such as README?

2022-03-15 07:21 UTC, Kangwhi-Kim requested changes

2022-03-15 07:21 UTC, Kangwhi-Kim commented on Makefile
> +	python3 -Bc "import pathlib; [p.rmdir() for p in pathlib.Path('.').rglob('__pycache__')]"
파일이 안에 있을 경우 rmdir구문 실행중 에러가 납니다.

2022-03-15 13:00 UTC, kbpark-onepredict commented on Makefile
> +	python3 -Bc "import pathlib; [p.rmdir() for p in pathlib.Path('.').rglob('__pycache__')]"
해당 폴더는 파이썬 실행 중에 발생하는 캐시파일이 저장되는 폴더이므로 의도적으로 해당 폴더에 파일을 넣지 않는 이상 pyc나 pyo외에는 다른 확장자의 파일이 들어갈 수 없습니다.
따라서 해당 폴더 내의 pyc와 pyo를 다 지운 후에는 폴더 지워지게 됩니다.
따라서 일반적인 make test, make clean 등의 작업에서는 에러가 발생할 일이 없습니다.

2022-03-16 00:40 UTC, Kangwhi-Kim requested changes

2022-03-16 00:40 UTC, Kangwhi-Kim commented on Makefile
> +	python3 -Bc "import pathlib; [p.rmdir() for p in pathlib.Path('.').rglob('__pycache__')]"
그렇군요. 사실, git의 tracking을 피할려고 commit하기 싫은 파일들은 __pycache__에 넣는데 오히려  에러가 나는게 좋겠네요. 감사합니다.

2022-03-16 01:10 UTC, kyunghwan-onepredict approved these changes
추가 감사합니다!

2022-03-16 02:13 UTC, Kangwhi-Kim approved these changes
버그 처리해주셔서 감사합니다

2022-03-16 02:14 UTC, merged